import type { Metadata } from "next";
import "./globals.css";

import { Cormorant } from "next/font/google";

const cormorant = Cormorant({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-cormorant",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${cormorant.variable} ${cormorant.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
